import { useState } from 'react';
import type { Locale } from './i18n';
import { HabitProgress } from './tracker';
import { ThemeSelect } from './theme';

type Props = { locale: Locale; onLocale: (locale: Locale) => void; loading: boolean; signedIn: boolean; canSignIn: boolean; authError: boolean; onStart: () => void; onPreview: () => void };
export function Landing({ locale, onLocale, loading, signedIn, canSignIn, authError, onStart, onPreview }: Props) {
  const ko = locale === 'ko';
  const [count, setCount] = useState(1);
  const cta = loading ? (ko ? '잠시만요…' : 'One moment…') : signedIn ? (ko ? '내 기록으로 돌아가기' : 'Open my journal') : (ko ? 'Google로 시작하기' : 'Start with Google');
  const start = <button className="landing-cta" disabled={loading || (!signedIn && !canSignIn)} onClick={onStart}>{cta}<span aria-hidden="true">↗</span></button>;
  return <div className="landing-site" id="welcome">
    <header className="landing-header"><a href="#welcome" className="landing-brand"><img src="/icon.svg" width="32" height="32" alt="" />Life Journal<span>a little, every day</span></a><div className="landing-header-actions"><ThemeSelect locale={locale} /><a href="#how-it-works">{ko ? '사용 방법' : 'How it works'}</a><label><span className="sr-only">{ko ? '언어' : 'Language'}</span><select value={locale} onChange={event => onLocale(event.target.value as Locale)}><option value="ko">한국어</option><option value="en">English</option></select></label></div></header>
    <main>
      <section className="landing-hero landing-wrap">
        <div className="landing-hero-copy"><p className="landing-kicker">YOUR DAYS, TAKING SHAPE</p><h1>{ko ? <>하루를 적고,<br />나를 <em>채워가요.</em></> : <>Write your day.<br /><em>Grow into you.</em></>}</h1><p className="landing-lead">{ko ? '흘려보내기 아쉬운 생각부터, 다시 시작하고 싶은 작은 습관까지. 나의 하루가 차곡차곡 쌓이는 공간.' : 'For thoughts worth keeping and little habits worth returning to. A space to see your days add up.'}</p>{start}<p className="landing-fine">{ko ? '나만 볼 수 있는 기록 · 한국어와 English' : 'Private entries · Korean and English'}</p>{!canSignIn && <button className="landing-text-button" onClick={onPreview}>{ko ? '기록 화면 체험하기 →' : 'Try the journal →'}</button>}{authError && <p role="alert" className="landing-error">{ko ? '로그인이 완료되지 않았어요. 다시 시도해 주세요.' : 'Sign-in did not finish. Please try again.'}</p>}</div>
        <div className="landing-notebook" aria-label={ko ? '일기와 습관 화면 예시' : 'Example journal and habit'}><div className="notebook-top"><span>MY LITTLE JOURNAL</span><span>{ko ? '화면 예시' : 'EXAMPLE'}</span></div><p className="notebook-date">{ko ? '어느 가을날의 기록' : 'A note from an autumn day'}</p><h2>{ko ? '오늘은 조금 걸었다.' : 'A little walk today.'}</h2><p className="notebook-prose">{ko ? '아침 공기가 좋아서 한 정거장 먼저 내렸다. 바쁘다는 핑계로 잊고 있었던 기분. 이번 주에는 네 번, 나를 위해 걸어보기.' : 'Got off one stop early for the morning air. A small thing I had forgotten to make time for. This week: four walks, just for me.'}</p><div className="notebook-rule" /><div className="notebook-habit"><div><span className="landing-kicker">ONE SMALL STEP</span><h3>{ko ? '나를 위한 산책' : 'A walk for myself'}</h3><p>{ko ? '이번 주 1 / 4회' : 'This week · 1 / 4 walks'}</p></div><HabitProgress count={1} target={4} korean={ko} /></div><span className="notebook-note">{ko ? '한 조각만큼, 잘했어요.' : 'One slice of progress. Yours.'}</span></div>
      </section>
      <section className="landing-process landing-wrap" id="how-it-works"><div className="landing-section-title"><p className="landing-kicker">WRITE → NOTICE → ACT</p><h2>{ko ? <>기록에서 실천까지,<br />하나의 흐름으로.</> : <>From a thought<br />to a little action.</>}</h2></div><div className="landing-steps">{(ko ? [['01','편하게 적어요','하루 한 편도, 생각날 때마다 여러 편도. 초안은 기기에 남고, 저장을 누르면 내 기록이 됩니다.'],['02','다음 행동을 꺼내요','글을 쓰다 떠오른 할 일을 계획에 직접 적어두세요. 기한을 정하고, 마친 일은 보관해요.'],['03','쌓인 날들을 돌아봐요','주간·월간 습관과 달력으로 나의 흐름을 봐요. 이력은 실제 첫 실천부터 쌓입니다.']] : [['01','Make a little room','One entry a day or several little notes. Drafts stay on your device; press Save to keep your entry.'],['02','Find your next step','Add an action to your plans yourself. Give it a due date, check it off, and archive it when you’re ready.'],['03','See your days add up','Weekly and monthly habits, a calendar, and a history that starts with your first check-in.']]).map(([number,title,body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="landing-reward"><div className="landing-wrap reward-layout"><div><p className="landing-kicker">SMALL IS STILL SOMETHING</p><h2>{ko ? <>어릴 적 색칠하던 사과.<br />이제는 나를 위해.</> : <>Remember filling in<br />your reward chart?</>}</h2><p>{ko ? '네 번이 목표라면 한 번에 사과의 ¼을 채워요. 완벽한 매일보다, 내가 해낸 한 번이 눈에 보이도록.' : 'Four steps to your goal? Each one fills a quarter of your apple. A small, visible reminder of what you did.'}</p></div><div className="reward-demo"><span className="landing-kicker">{ko ? '직접 눌러보세요 · 체험용' : 'TRY IT · SAMPLE ONLY'}</span><HabitProgress count={count} target={4} korean={ko} /><p aria-live="polite">{ko ? `이번 주 ${count} / 4회` : `This week · ${count} / 4`}</p><button className="landing-cta" onClick={() => setCount(value => value === 4 ? 0 : value + 1)}>{count === 4 ? (ko ? '다시 채워보기' : 'Try again') : (ko ? '+ 한 번 실천했어요' : '+ I did it today')}</button><small>{ko ? '실제 기록에는 저장되지 않아요.' : 'This demo does not save a check-in.'}</small></div></div></section>
      <section className="landing-roadmap landing-wrap"><div className="landing-section-title"><p className="landing-kicker">COMING SOON · {ko ? '준비 중' : 'IN THE WORKS'}</p><h2>{ko ? '기록의 다음 가능성.' : 'A little more help, ahead.'}</h2><p>{ko ? '아래 기능은 아직 사용할 수 없어요. 기록을 이어가는 데 도움이 될 기능을 준비하고 있습니다.' : 'These features are not available yet. We’re planning thoughtful ways to help you keep going.'}</p></div><div className="roadmap-grid">{(ko ? [['AI 정리','일기에서 다음 행동의 후보를 발견하고 제안해요.'],['리마인더','이메일·브라우저 알림과 원하는 시간 설정.'],['대화형 회고','내 기록을 바탕으로 질문하고 돌아보는 챗봇.'],['MCP 연결','개발자가 자신의 도구와 기록을 연결하는 방법.']] : [['AI suggestions','Discover possible next actions in your journal.'],['Reminders','Email and browser notifications on your schedule.'],['Reflect in conversation','Ask questions and reflect with your own entries.'],['MCP connection','Connect your journal with your own developer tools.']]).map(([title,body])=><article key={title}><span>COMING SOON</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="landing-faq landing-wrap"><h2>{ko ? '시작하기 전에.' : 'Before your first page.'}</h2>{(ko ? [['일기를 매일 써야 하나요?','아니요. 생각날 때 한 줄부터 써도 좋아요. 하루에 여러 기록을 남길 수도 있어요.'],['기록은 누가 볼 수 있나요?','일기와 계획은 내 계정에 연결됩니다. 다른 사용자에게 공개하는 기능은 제공하지 않아요.'],['앱을 설치해야 하나요?','설치 없이 모바일과 데스크톱 브라우저에서 사용할 수 있어요. Google 계정으로 시작하세요.'],['내 기록을 꺼내갈 수 있나요?','내 공간의 설정에서 일기를 Markdown 파일로 내보낼 수 있어요.']] : [['Do I have to write every day?','No. Start with a line whenever you feel like it, or write several entries in a day.'],['Who can see my entries?','Your entries and plans belong to your account. There is no feature for publishing them to other users.'],['Do I need to install an app?','Use your mobile or desktop browser. Start with your Google account; no installation required.'],['Can I take my entries with me?','Export your journal as Markdown from the settings in My space.']]).map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</section>
      <section className="landing-closing landing-wrap"><p className="landing-kicker">A LITTLE, EVERY DAY</p><h2>{ko ? '오늘은 한 줄이면 충분해요.' : 'A line is enough for today.'}</h2>{start}</section>
    </main><footer className="landing-footer landing-wrap"><strong>Life Journal</strong><span>{ko ? '나의 언어로, 나의 속도로.' : 'Your words. Your pace.'}</span><a href="#welcome">{ko ? '처음으로 ↑' : 'Back to top ↑'}</a></footer>
  </div>;
}
